<h1 style="text-align:center; font-size: 5em;">Numpy Basics</h1>

<hr style="border:2px solid">
<h1 style="text-align:center; font-size: 3em;">Workbook Overview</h1>
<hr style="border-top:1px dashed">
<ul>
        <li><a href="#anchorSetup">Lab Setup and Explanation</a></li> 
        <li><a href="#anchorndArray">Creating Arrays</a></li> 
        <li><a href="#anchorIndexSlice">Indexing and Slicing</a></li> 
</ul>

<div class="alert alert-block alert-warning">
    <b>Task 0: Import Numpy</b>
</div>

In [1]:
import numpy as np

You are welcome to make as many extra code cells as you would like, just remember to clean up your notebook before submitting your work. 

The easier your work is to check, the more we can focus on giving feedback instead of hunting down answers.

With that being said, we hope you have fun with this lab!~

<a name="anchorndArray" style="position:absolute;"></a>
<hr style="border:2px solid">

## Section 1: ndArrays
<hr style="border-top:1px dashed">
In this section, the tasks are oriented around ndArray manipulation using functions and mathematical operations.

Please answer the tasks in the code cells provided below them.

<div class="alert alert-block alert-warning">
    <b>Task 01: Create an array of 10 zeros </b>
</div>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<div class="alert alert-block alert-warning">
    <b>Task 02: Create an array of 10 ones </b>
</div>

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<div class="alert alert-block alert-warning">
    <b>Task 03: Create an array of 10 fives </b>
</div>

In [8]:
np.full((10),5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

<div class="alert alert-block alert-warning">
    <b>Task 04: Create an array of the integers from 10 to 50s </b>
</div>

In [9]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

<div class="alert alert-block alert-warning">
    <b>Task 05: Create an array of all the even integers from 10 to 50 </b>
</div>

In [10]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

<div class="alert alert-block alert-warning">
    <b>Task 06: Create a 3x3 matrix with values ranging from 0 to 8 </b>
</div>

In [19]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<div class="alert alert-block alert-warning">
    <b>Task 07: Create a 3x3 identity matrix </b>
</div>

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div class="alert alert-block alert-warning">
    <b>Task 08: Use NumPy to generate a random number between 0 and 1 </b>
</div>

In [25]:
np.random.randint(0,1)

0

<div class="alert alert-block alert-warning">
    <b>Task 09: Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution </b>
</div>

In [26]:
np.random.normal(0,1,25)

array([ 1.37194759,  1.85373328, -1.18446842, -0.97585874, -0.77546308,
        0.13531624,  0.42732799, -1.12625188,  0.24087881,  0.27211769,
       -0.30718891,  0.49466982,  0.11379869,  1.07218659, -0.47086924,
        1.41095588,  0.66227241, -1.12504773,  1.22701483, -0.50236562,
        2.09417867,  0.9230597 , -0.80948318,  0.15481407, -1.86252104])

<div class="alert alert-block alert-warning">
    <b>Task 10: Create the following matrix, create a 10 x 10 matrix with values going from 0.01 to 1, the column step size is 0.01.</b>
</div>

In [35]:
np.arange(0.01,1.01,0.01).reshape(10,10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

<div class="alert alert-block alert-warning">
    <b>Task 11: Create an array of 20 linearly spaced points between 0 and 1 </b>
</div>

In [36]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<a name="anchorIndexSlice" style="position:absolute;"></a>
<hr style="border:2px solid">

## Section 2: Numpy Indexing and Slicing
<hr style="border-top:1px dashed">
In this section, the tasks are oriented around ndArray manipulation using indexing and slicing. You will be given a few matrices and will be tasked to replicate the resulting matrix outputs.

In [37]:
# This is the array you will be working with for the other tasks below
lab = np.arange(1,26).reshape(5,5)
print(lab)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


<div class="alert alert-block alert-info">
    <b>You will be using the "lab" array for the Tasks below. Here is what the array looks like:</b>
</div>

$
{\Large lab>>}\hspace{0.1cm}
\begin{bmatrix}     
   [\hspace{0.2cm}1,\hspace{0.2cm}2,\hspace{0.2cm}3,\hspace{0.2cm}4,\hspace{0.2cm}5], 
\\ [\hspace{0.2cm}6,\hspace{0.2cm}7,\hspace{0.2cm}8,\hspace{0.2cm}9,10], 
\\ [11, 12, 13, 14, 15],
\\ [16, 17, 18, 19, 20],
\\ [21, 22, 23, 24, 25]\hspace{0.1cm}
\end{bmatrix}
$

<div class="alert alert-block alert-warning">
    <b>Task 12: Using the provided "lab" array, replicate the following array ouput:</b>
</div>

$
{\Large array}\hspace{0.2cm}{\Large output >>}\hspace{0.1cm}
\begin{bmatrix} 
   {\Large 16, 17, 18, 19, 20 }
\end{bmatrix}
$

In [42]:
lab[3,:]

array([16, 17, 18, 19, 20])

<div class="alert alert-block alert-warning">
    <b>Task 13: Using the provided "lab" array, replicate the following array ouput:</b>
</div>

$
{\Large array}\hspace{0.2cm}{\Large output >>}\hspace{0.1cm}{\Large 15}
$

In [44]:
lab[2,4]

15

<div class="alert alert-block alert-warning">
    <b>Task 14: Using the provided "lab" array, replicate the following array ouput:</b>
</div>

$
{\Large array}\hspace{0.2cm}{\Large output >>}\hspace{0.1cm}
\begin{bmatrix} 
   [12, 13, 14, 15], 
\\ [17, 18, 19, 20], 
\\ [22, 23, 24, 25]\hspace{0.1cm}
\end{bmatrix}
$

In [59]:
lab[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

<div class="alert alert-block alert-warning">
    <b>Task 15: Using the provided "lab" array, replicate the following array ouput:</b>
</div>

$
{\Large array}\hspace{0.2cm}{\Large output >>}\hspace{0.1cm}
\begin{bmatrix} 
   [12], 
\\ [17], 
\\ [22]\hspace{0.1cm}
\end{bmatrix}
$


In [57]:
lab[2:,1]

array([12, 17, 22])

<div class="alert alert-block alert-warning">
    <b>Task 16: Using the provided "lab" array, replicate the following array ouput:</b>
</div>

$
{\Large array}\hspace{0.2cm}{\Large output >>}\hspace{0.1cm}
\begin{bmatrix}     
   [\hspace{0.2cm}1,\hspace{0.2cm}2,\hspace{0.2cm}3,\hspace{0.2cm}4,\hspace{0.2cm}5], 
\\ [11, 12, 13, 14, 15],
\\ [21, 22, 23, 24, 25]\hspace{0.1cm}
\end{bmatrix}
$

In [68]:
lab[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

<div class="alert alert-block alert-warning">
    <b>Task 17: Using the provided "lab" array, replicate the following array ouput:</b>
</div>

$
{\Large array}\hspace{0.2cm}{\Large output >>}\hspace{0.1cm}
\begin{bmatrix} 
   {\Large \hspace{0.1cm}1,\hspace{0.1cm}7,\hspace{0.1cm}13,\hspace{0.1cm}19,\hspace{0.1cm}25\hspace{0.1cm}}
\end{bmatrix}
$

In [71]:
lab.diagonal()

array([ 1,  7, 13, 19, 25])

<div class="alert alert-block alert-info">
    <details><summary><b>Want a Hint for Task 17?</b><br>>> Click on this box << </summary>

        There are two ways to solve this:
        - use lists for the positions, similar to task 13
        - use a stepper (range()) to create the lists

</details>
</div>

<div class="alert alert-block alert-warning">
    <b>Extra Task 18: Get the sum of all the values in the lab array</b>
</div>

$
{\Large desired}\hspace{0.2cm}{\Large output >>}\hspace{0.2cm}{\Large 325}
$

In [72]:
np.sum([lab])

325

<div class="alert alert-block alert-warning">
    <b>Extra Task 19: Get the standard deviation of the values in the lab array.</b>
</div>

$
{\Large desired}\hspace{0.2cm}{\Large output >>}\hspace{0.2cm}{\Large 7.21...}
$

In [73]:
np.std([lab])

7.211102550927978

<div class="alert alert-block alert-warning">
    <b>Extra Task 20: Get the sum of all the columns in the lab array.</b>
</div>


$
{\Large desired}\hspace{0.2cm}{\Large output >>}\hspace{0.1cm}
\begin{bmatrix} 
   {\Large 55, 60, 65, 70, 75}
\end{bmatrix}
$

In [80]:
lab.sum(axis=0)

array([55, 60, 65, 70, 75])

<hr style="border:2px solid">